export const REGISTER_LOADING = 'REGISTER_LOADING';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'REGISTER_FAILURE';

export const VERIFY_EMAIL_LOADING = ' VERIFY_EMAIL_LOADING';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAILURE = 'VERIFY_EMAIL_FAILURE';

// PROFILE
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const PROFILE_FAILURE = 'PROFILE_FAILURE';
export const PROFILE_ERROR = 'PROFILE_ERROR';

// INTERESTS
export const GET_INTEREST = 'GET_INTEREST';
export const UPDATE_INTEREST = 'UPDATE_INTEREST';
export const INTEREST_ERROR = 'INTEREST_ERROR';

// upload Pdf
export const GET_UPLOAD_PDF = 'GET_UPLOAD_PDF';
export const UPLOAD_PDF = 'UPLOAD_PDF';
export const UPDATE_UPLOAD_PDF = 'UPDATE_UPLOAD_PDF';
export const UPLOAD_PDF_ERROR = 'UPLOAD_PDF_ERROR';
